name: Sniper Userbot

on:
  schedule:
    # ⚠️ AJUSTE DE HORÁRIO AQUI ⚠️
    # O Cron usa UTC. Brasil está em UTC-3.
    # Se o jogo é às 20:30 BR, o bot deve ligar às 20:20 BR.
    # 20:20 BR = 23:20 UTC.
    # Quinta-feira = 4
    - cron: '20 23 * * 4' 
  
  # Permite testar clicando num botão
  workflow_dispatch:

jobs:
  run-sniper:
    runs-on: ubuntu-latest
    # Garante que ele não morra antes da hora (aguenta até 20 min)
    timeout-minutes: 20 
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar libs
        run: pip install -r requirements.txt

      - name: Disparar Sniper
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SESSION_JAQUELINE: ${{ secrets.SESSION_JAQUELINE }}
          SESSION_LARISSA: ${{ secrets.SESSION_LARISSA }}
          SESSION_KATIA: ${{ secrets.SESSION_KATIA }}
          SESSION_PRISCILA: ${{ secrets.SESSION_PRISCILA }}
          SESSION_YASMIN: ${{ secrets.SESSION_YASMIN }}
          SESSION_MONICA: ${{ secrets.SESSION_MONICA }}
          SESSION_JULIANE: ${{ secrets.SESSION_JULIANE }}
          SESSION_SARA: ${{ secrets.SESSION_SARA }}
          SESSION_LUCIANA: ${{ secrets.SESSION_LUCIANA }}
          SSESSION_JANAINE: ${{ secrets.SESSION_JANAINE }}
        run: |
          # Define fuso horário de SP para o Python saber a hora certa
          export TZ="America/Sao_Paulo"
          python main.py