name: Deploy para Vultr Miami

on:
  push:
    branches:
      - main  # Se a sua branch principal chamar master, mude aqui
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pegar o código mais recente
        uses: actions/checkout@v3

      - name: 🚚 Enviar arquivos para Miami
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/root/bot_telegram"

      - name: 🔄 Reiniciar o Bot no PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/bot_telegram
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pm2 restart maestro || pm2 start main.py --name "maestro" --interpreter ./venv/bin/python
            pm2 save